insert into user_equipe values
("UnicornRainbow", "Paul", "$2y$10$3gpxAkF3BtHwYCp3cUzNkueO.RclFC3j4RaILi8NhmaQ7/5WGsUJW");

INSERT INTO `escapegame` (`eg_id`, `eg_nom`, `eg_description_short`, `eg_description_long`, `eg_temps_max`, `eg_image`)
VALUES  (NULL, 'Escape the Void', 'For a routine mission, today sucks. The ship\'s oxygen tank has been breached, the command computer intelligence is not awnsering,except to repeat that 85% of oxygen tank related incidents not controlled within the first 15 minutes lead to the death of all crew members. </br>Just another day on the job. Maybe tomorrow you should call in sick', 'This escape game is suitable for any player, including those without prior experience with virtual escape games.</br></br>Where do I go</br>When I\'m feeling so lost and I don\'t want to be found?</br>When I\'m looking and listening for that peace in my heart.</br>But I know I\'ll never hear that sound.</br>Where do I go?</br>Where do I go when I\'m trying to laugh but all I can do I cry?</br>I\'m trying to keep on living because I\'m not ready to die.</br>Where do I go because the sun never seems to shine?</br>Can you give me my life back\' it\'s not yours, it\'s mine?</br>How do I keep going, how do I fight this fight?</br>I\'m tired of feeling beat down, but I\'m trying with all my might!</br>Where do I go when my head hangs so low?</br>Please give me an answer because I just don\'t know!</br>Where do I go?</br>Does it take very long</br>For me to find that peace and a place where I belong?</br>I need you to help me, help me to take a stand.</br>I\'m scared to do it by myself; will you please take my hand?</br>Where do I go? Where do I go? Where do I go?</br>Do you know?', '900', 'Command.jpg'),
        (NULL, 'Escape the Void II', 'Now that you\'ve left your doomed ship in the escape pod, you have to contact the fleet to be rescued.</br>All the communication device is recieving is static and cryptic sounds. The command computer is back on, but rambling nonsense constantly. </br></br>There was that desk job position that freed itself back at the base. Maybe you should listen to your mother and apply there if you get home.', 'This escape game is suitable for any player, including those without prior experience with virtual escape games.</br></br></br>Orange and Pink shoot across the sky,</br>I can see it from where I lie,</br>The sun is setting, going to sleep,</br>The dark surrounds, like the ocean deep,</br></br>The stars come, twinkling lights,</br>Glittering diamonds, What a sight,</br>I lie in the grass and up I stare,</br>My body goes numb as I forget all my cares</br></br>I like to gaze up at the stars,</br>So I can forget my cares and all my scars,</br></br>I have no one to look after me,</br>The real me is someone no one can see,</br>So I\'ll wait until I find some sort of love,</br>And until then it\'s just me and the stars above.</br>', '600', 'asteroid.jpg'),
        (NULL, 'Escape the Void III', 'When you stare to hard into the void, the void stares right back. Maybe the Space consortium is\'nt the only one flying ship. It definently was not them on the transmission. To hell with pension or the employee of the month bonus, whoever gets you out of there is welcome. Lets just hope they\'re human' , 'This escape game is suitable for any player, including those without prior experience with virtual escape games.</br></br>Where do I go</br>When I\'m feeling so lost and I don\'t want to be found?</br>When I\'m looking and listening for that peace in my heart.</br>But I know I\'ll never hear that sound.</br>Where do I go?</br>Where do I go when I\'m trying to laugh but all I can do I cry?</br>I\'m trying to keep on living because I\'m not ready to die.</br>Where do I go because the sun never seems to shine?</br>Can you give me my life back\' it\'s not yours, it\'s mine?</br>How do I keep going, how do I fight this fight?</br>I\'m tired of feeling beat down, but I\'m trying with all my might!</br>Where do I go when my head hangs so low?</br>Please give me an answer because I just don\'t know!</br>Where do I go?</br>Does it take very long</br>For me to find that peace and a place where I belong?</br>I need you to help me, help me to take a stand.</br>I\'m scared to do it by myself; will you please take my hand?</br>Where do I go? Where do I go? Where do I go?</br>Do you know?', '900', 'lostlights.jpg'),
        (NULL, 'The Byron Mansion', 'WIP - in development', 'This escape game is suitable for any player, including those without prior experience with virtual escape games.</br></br></br>Orange and Pink shoot across the sky,</br>I can see it from where I lie,</br>The sun is setting, going to sleep,</br>The dark surrounds, like the ocean deep,</br></br>The stars come, twinkling lights,</br>Glittering diamonds, What a sight,</br>I lie in the grass and up I stare,</br>My body goes numb as I forget all my cares</br></br>I like to gaze up at the stars,</br>So I can forget my cares and all my scars,</br></br>I have no one to look after me,</br>The real me is someone no one can see,</br>So I\'ll wait until I find some sort of love,</br>And until then it\'s just me and the stars above.</br>', '600', 'stmpnk.jpg'),
        (NULL, 'The Lord\'s Ghost', 'WIP - In development', 'This escape game is suitable for any player, including those without prior experience with virtual escape games.</br></br>Where do I go</br>When I\'m feeling so lost and I don\'t want to be found?</br>When I\'m looking and listening for that peace in my heart.</br>But I know I\'ll never hear that sound.</br>Where do I go?</br>Where do I go when I\'m trying to laugh but all I can do I cry?</br>I\'m trying to keep on living because I\'m not ready to die.</br>Where do I go because the sun never seems to shine?</br>Can you give me my life back\' it\'s not yours, it\'s mine?</br>How do I keep going, how do I fight this fight?</br>I\'m tired of feeling beat down, but I\'m trying with all my might!</br>Where do I go when my head hangs so low?</br>Please give me an answer because I just don\'t know!</br>Where do I go?</br>Does it take very long</br>For me to find that peace and a place where I belong?</br>I need you to help me, help me to take a stand.</br>I\'m scared to do it by myself; will you please take my hand?</br>Where do I go? Where do I go? Where do I go?</br>Do you know?', '900', 'stmpnk.jpg'),
        (NULL, 'Ada\'s Father' , 'WIP - In development', 'This escape game is suitable for any player, including those without prior experience with virtual escape games.</br></br></br>Orange and Pink shoot across the sky,</br>I can see it from where I lie,</br>The sun is setting, going to sleep,</br>The dark surrounds, like the ocean deep,</br></br>The stars come, twinkling lights,</br>Glittering diamonds, What a sight,</br>I lie in the grass and up I stare,</br>My body goes numb as I forget all my cares</br></br>I like to gaze up at the stars,</br>So I can forget my cares and all my scars,</br></br>I have no one to look after me,</br>The real me is someone no one can see,</br>So I\'ll wait until I find some sort of love,</br>And until then it\'s just me and the stars above.</br>', '600', 'stmpnk.jpg');
INSERT INTO `enigme` (`eng_id`, `eg_id`, `eng_content`) 
VALUES (NULL, '1', 'Où l\'astronaute doit ouvrir la porte pour prendre la navette de secours.'),
('2', '1', 'Maintenant que la porte est ouverte, il faut réussir à lancer la navette, loin du vaisseau sur le point d\'exploser');

INSERT INTO `bouton` (`eng_id`, `btn`, `btn_type`, `btn_active`, `btn_expected`, `btn_name`, `btn_content`)
VALUES ('1', '1', 'Textual', '1', '0', 'Lumière', "Dans le centre de commande, tous les écrans se sont éteint. L\'interface d\'urgence est éclairée par une lampe qui clignote par saccades de 4 flashs, grésille, et s\'éteint de temps en temps."),
('1', '4', 'Textual', '0', '0', 'Alerte', 'Vaisseau >> Rappel des alertes : Aucune commande général ne répond. Les tank à oxygène ont été touchés. Les statistique de bord vous donnent une espérance de vie de 15min. Ne paniquez pas.'),
('2', '1', 'Textual', '1', '0', 'Porte', 'Vaisseau >> Porte ouverte. Préparez le décollage et fermez la porte.'),
('2', '2', 'Textual', '0', '0', 'Load', 'Vaisseau >> l\'Intelligence artificielle du vaisseau a été chargée dans la navette de secours.</br>Vaisseau >> ERR4532 L\'IA du vaisseau est défectueuse. Il est déconseillé de l\'activer'),
('2', '3', 'Textual', '0', '1', 'AI ', 'Vaisseau >> ERR5698 IA défectueuse</br>Vaisseau : IA >> Bonjour utilisateur... Veuillez décoller au plus vite, votre vie est en danger. Laissez moi vous aider</br>Vaisseau >> OVERRIDE IA : IA défectueuse. mise en quarantine.'),
('2', '4', 'Textual', '0', '1', 'Démarrer', 'Vaisseau >> Lancement prêt. Attention, l\'utilisation de cette navette de secours doit suivre le protocole exacte du manuel sous peine d\'annulation de garantie.'),
('1', '2', 'Textual', '0', '1', 'Alerte', 'Vaisseau >> Vos Alertes sont : Risque de mort 79%. Vaisseau endommagé. Réservoir d\'oxygène défectueux. Ne paniquez pas, car un équipage paniqué a 99.99% de chances de mourir dans les 15 premières minutes.</br>Vaisseau >> Le mode alerte passe tout le vaisseau en mode déverrouillage manuel. Pour votre sécurité, veuillez le désactiver.'),
('1', '3', 'Textual', '0', '1', 'Porte', 'Vaisseau >> ERR4598 les portes sont verrouillées. Le système de verrouillage est bloqué pendant la durée de la situation dangereuse pour votre sécurité.');